### PR TITLE
FPET-13 changes to display case list

### PR DESCRIPTION
**Pull request by sairamkantheti1**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/FPET-13 
https://tools.hmcts.net/jira/browse/FPET-12

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by priteshkr — COMMENTED** [review]
1) In CallbackController.java :  Pass caseData and extract Map in the service. Do not pass two arguments at line 303
2) In SeacrchCaseDataService , Correct the loggers at line 45.

**Comment by sairamkantheti1** [comment]
review changes are committed

**Review by priteshkr — APPROVED** [review]
Changes looks ok now.

**Review by priteshkr — APPROVED** [review]
Changes look fine

**Review by shashisk97 — APPROVED** [review]
Changes looks good, always add a JIRa reference in the PR

**Pull request merged**
